version: '3.9'

services:
  db:
    image: postgres:12
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PG_USER} -d $${PG_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  apiapp:
    build:
      context: ./apiapp
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: apiapp
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  webapp:
    build:
      context: ./webapp
      args:
        NODE_ENV: ${NODE_ENV}
    container_name: webapp
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - apiapp

volumes:
  pgdata: {}